import { Hono } from 'hono';
import { getCookie, setCookie, deleteCookie } from 'hono/cookie';
import { z } from 'zod';
import { seed, type Store, type Role, type User } from '../../packages/shared/model';
import { hash, seal, unseal, secret } from './crypto';
export type Repository = { read: () => Promise<Store>; change: <T>(fn: (data: Store) => Promise<T> | T) => Promise<T> };
export const permissions: Record<string, Role[]> = { customers: ['owner', 'administrator', 'support'], licenses: ['owner', 'administrator', 'support'], manageLicenses: ['owner', 'administrator'], devices: ['owner', 'administrator', 'support'], orders: ['owner', 'administrator', 'support'], billing: ['owner', 'administrator'], products: ['owner', 'administrator', 'product_manager'], content: ['owner', 'administrator', 'product_manager'], team: ['owner'], settings: ['owner'], audit: ['owner', 'administrator'] };
export function memoryRepo(): Repository { let data = seed(); let queue = Promise.resolve(); return { read: async () => structuredClone(data), change: fn => { const job = queue.then(async () => { const next = structuredClone(data); const result = await fn(next); data = next; return result; }); queue = job.then(() => { }, () => { }); return job; } }; }
export function createApp(repo: Repository, encryptionKey: string, { preview = false, origin = 'http://127.0.0.1:4321' } = {}) {
    const app = new Hono<{ Variables: { user: User } }>(); const sessions = new Map<string, { userId: string; expires: number }>();
    const audit = (s: Store, user: User, action: string, target: string) => s.audit.unshift({ id: crypto.randomUUID(), actor: user.name, action, target, createdAt: new Date().toISOString() });
    app.use('/api/*', async (c, next) => { c.header('Cache-Control', 'no-store'); c.header('X-Content-Type-Options', 'nosniff'); if (!['GET', 'HEAD', 'OPTIONS'].includes(c.req.method) && !c.req.path.startsWith('/api/agent/') && c.req.header('origin') !== origin) return c.json({ error: 'Request origin is not allowed.' }, 403); if (Number(c.req.header('content-length') || 0) > 32768) return c.json({ error: 'Request is too large.' }, 413); await next(); });
    app.onError((e, c) => c.json({ error: e instanceof z.ZodError ? e.errors.map(e => e.message).join(' ') : 'The request could not be completed.' }, e instanceof z.ZodError ? 400 : 500));
    app.get('/api/health', c => c.json({ mode: preview ? 'local-preview' : 'unconfigured', livePayments: false }));
    app.get('/api/catalog', async c => { const s = await repo.read(); return c.json({ products: s.products.filter(p => p.status === 'published'), settings: s.settings, preview }); });
    app.get('/api/auth/config', c => c.json({ mode: 'preview', preview, registration: false }));
    app.post('/api/preview/session', async c => { if (!preview) return c.json({ error: 'Preview is disabled.' }, 404); const { role } = z.object({ role: z.enum(['owner', 'customer', 'support', 'product_manager']) }).parse(await c.req.json()); const s = await repo.read(); const user = s.users.find(u => u.role === role && u.status === 'active'); if (!user) return c.json({ error: 'Preview account unavailable.' }, 403); const token = secret(); sessions.set(token, { userId: user.id, expires: Date.now() + 3600_000 }); setCookie(c, 'norvi_preview', token, { httpOnly: true, sameSite: 'Strict', path: '/', maxAge: 3600 }); await repo.change(s => { s.users.find(u => u.id === user.id)!.lastLogin = new Date().toISOString(); }); return c.json({ user }); });
    app.post('/api/auth/logout', c => { sessions.delete(getCookie(c, 'norvi_preview') || ''); deleteCookie(c, 'norvi_preview', { path: '/' }); return c.json({ ok: true }); });
    app.post('/api/auth/:action', c => c.json({ error: 'Account services are not connected yet. Use the clearly labeled local preview to explore the website; do not enter a real password.' }, 503));
    app.use('/api/*', async (c, next) => { if (!preview) return c.json({ error: 'Live services are not configured.' }, 503); if (c.req.path.startsWith('/api/agent/')) return next(); const session = sessions.get(getCookie(c, 'norvi_preview') || ''); const s = await repo.read(); const user = session && session.expires > Date.now() ? s.users.find(u => u.id === session.userId && u.status === 'active') : null; if (!user) return c.json({ error: 'Sign in to continue.' }, 401); c.set('user', user); await next(); });
    app.get('/api/me', c => c.json({ user: c.get('user'), preview: true }));
    app.get('/api/account', async c => { const s = await repo.read(); const id = c.get('user').id; return c.json({ user: c.get('user'), licenses: s.licenses.filter(l => l.userId === id).map(({ keyHash, encryptedKey, ...l }) => l), orders: s.orders.filter(o => o.userId === id), tickets: s.tickets.filter(t => t.userId === id), emails: s.emails.filter(e => e.userId === id) }); });
    app.patch('/api/me', async c => { const { name } = z.object({ name: z.string().trim().min(2).max(80) }).parse(await c.req.json()); await repo.change(s => { s.users.find(u => u.id === c.get('user').id)!.name = name; }); return c.json({ ok: true }); });
    app.post('/api/preview/purchase', async c => { const { productId } = z.object({ productId: z.string() }).parse(await c.req.json()); const user = c.get('user'); const result = await repo.change(async s => { const p = s.products.find(p => p.id === productId && p.status === 'published'); if (!p || p.releaseStatus === 'development') return { error: 'Product is unavailable for purchase while in development.' }; const existing = s.orders.find(o => o.userId === user.id && o.productId === productId && o.status === 'simulated'); if (existing) return { order: existing }; const key = 'NORVI_' + secret(); const id = crypto.randomUUID(); s.licenses.push({ id, userId: user.id, productId, status: 'active', keyHash: await hash(key), encryptedKey: await seal(key, encryptionKey), suffix: key.slice(-6), createdAt: new Date().toISOString(), device: null, expiresAt: null }); const order = { id: crypto.randomUUID(), userId: user.id, productId, status: 'simulated' as const, amount: 'Preview — no charge', createdAt: new Date().toISOString(), licenseId: id }; s.orders.push(order); s.emails.push({ id: crypto.randomUUID(), userId: user.id, orderId: order.id, status: 'Preview only · not sent', createdAt: order.createdAt }); audit(s, user, 'Simulated purchase', p.name); return { order }; }); return c.json(result, 'error' in result ? 400 : 200); });
    app.post('/api/licenses/:id/reveal', async c => { const s = await repo.read(); const user = c.get('user'); const license = s.licenses.find(l => l.id === c.req.param('id') && (l.userId === user.id || user.role === 'owner')); if (!license) return c.json({ error: 'License not found.' }, 404); await repo.change(s => audit(s, user, 'Revealed preview key', license.id)); return c.json({ key: await unseal(license.encryptedKey, encryptionKey) }); });
    app.post('/api/licenses/:id/device-reset', async c => { const result = await repo.change(s => { const user = c.get('user'); const l = s.licenses.find(l => l.id === c.req.param('id')); if (!l || (l.userId !== user.id && !permissions.devices.includes(user.role))) return false; l.device = null; audit(s, user, 'Reset device', l.id); return true; }); return result ? c.json({ ok: true }) : c.json({ error: 'License not found.' }, 404); });
    app.post('/api/licenses/:id/download', c => c.json({ error: 'No agent release has been uploaded yet. Add the actual agent files before enabling downloads.' }, 409));
    app.post('/api/support', async c => { const data = z.object({ subject: z.string().trim().min(3).max(120), message: z.string().trim().min(10).max(3000) }).parse(await c.req.json()); await repo.change(s => s.tickets.unshift({ ...data, id: crypto.randomUUID(), userId: c.get('user').id, status: 'open', createdAt: new Date().toISOString() })); return c.json({ ok: true }); });
    app.use('/api/admin/*', async (c, next) => { if (c.get('user').role === 'customer') return c.json({ error: 'Staff permission required.' }, 403); await next(); });
    app.get('/api/admin/:section', async c => { const section = c.req.param('section'), user = c.get('user'); if (!(permissions[section] || []).includes(user.role)) return c.json({ error: 'Your role cannot access this section.' }, 403); const s = await repo.read(); if (section === 'customers') return c.json({ items: s.users.filter(u => u.role === 'customer').map(u => ({ ...u, purchases: s.orders.filter(o => o.userId === u.id && o.status === 'simulated').length, licenseCount: s.licenses.filter(l => l.userId === u.id).length })) }); if (section === 'licenses') return c.json({ items: s.licenses.map(({ keyHash, encryptedKey, ...l }) => ({ ...l, customer: s.users.find(u => u.id === l.userId)?.name, product: s.products.find(p => p.id === l.productId)?.name })) }); if (section === 'orders' || section === 'billing') return c.json({ items: s.orders.map(o => ({ ...o, customer: s.users.find(u => u.id === o.userId)?.name, product: s.products.find(p => p.id === o.productId)?.name })) }); if (section === 'products') return c.json({ items: s.products }); if (section === 'team') return c.json({ items: s.users.filter(u => u.role !== 'customer'), invitations: s.invitations }); if (section === 'audit') return c.json({ items: s.audit, emails: s.emails }); if (section === 'settings' || section === 'content') return c.json({ settings: s.settings }); return c.json({ error: 'Not found' }, 404); });
    app.post('/api/admin/products', async c => { const user = c.get('user'); if (!permissions.products.includes(user.role)) return c.json({ error: 'Permission denied.' }, 403); const input = z.object({ id: z.string().optional(), name: z.string().trim().min(2).max(80), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'Use lowercase words separated by hyphens.'), category: z.string().min(2).max(80), tagline: z.string().min(3).max(140), description: z.string().min(5).max(2000), price: z.string().min(1).max(50), status: z.enum(['draft', 'published', 'archived']), releaseStatus: z.enum(['development', 'prelaunch']).optional(), features: z.array(z.string().max(120)).max(8), icon: z.enum(['workflow', 'message', 'sparkles']), color: z.enum(['lime', 'blue', 'purple']), requirements: z.string().max(400), version: z.string().max(40) }).parse(await c.req.json()); const result = await repo.change(s => { if (s.products.some(p => p.slug === input.slug && p.id !== input.id)) return { error: 'This URL is already used by another agent.' }; const p = { ...input, id: input.id || crypto.randomUUID(), updatedAt: new Date().toISOString() }; const index = s.products.findIndex(x => x.id === p.id); if (index >= 0) s.products[index] = p; else s.products.push(p); audit(s, user, 'Saved product (' + p.status + ')', p.name); return { product: p }; }); return c.json(result, 'error' in result ? 409 : 200); });
    app.post('/api/admin/licenses/:id/:action', async c => { const user = c.get('user'); if (!permissions.manageLicenses.includes(user.role)) return c.json({ error: 'Permission denied.' }, 403); const { reason } = z.object({ reason: z.string().trim().min(5).max(250) }).parse(await c.req.json()); const action = z.enum(['revoke', 'restore', 'rotate']).parse(c.req.param('action')); const result = await repo.change(async s => { const l = s.licenses.find(l => l.id === c.req.param('id')); if (!l) return false; if (action === 'rotate') { const key = 'NORVI_' + secret(); l.keyHash = await hash(key); l.encryptedKey = await seal(key, encryptionKey); l.suffix = key.slice(-6); } else l.status = action === 'revoke' ? 'revoked' : 'active'; l.device = null; audit(s, user, action + ': ' + reason, l.id); return true; }); return result ? c.json({ ok: true }) : c.json({ error: 'License not found.' }, 404); });
    app.patch('/api/admin/settings', async c => { const user = c.get('user'); if (!permissions.settings.includes(user.role)) return c.json({ error: 'Owner permission required.' }, 403); const data = z.object({ name: z.string().trim().min(2).max(60), headline: z.string().max(150), description: z.string().max(500), email: z.string().max(100), company: z.string().max(100), domain: z.string().max(150) }).parse(await c.req.json()); await repo.change(s => { s.settings = data; audit(s, user, 'Updated business settings', data.name); }); return c.json({ ok: true }); });
    app.patch('/api/admin/content', async c => { const user = c.get('user'); if (!permissions.content.includes(user.role)) return c.json({ error: 'Permission denied.' }, 403); const data = z.object({ headline: z.string().min(5).max(150), description: z.string().min(5).max(500) }).parse(await c.req.json()); await repo.change(s => { s.settings = { ...s.settings, ...data }; audit(s, user, 'Updated homepage content', 'Homepage'); }); return c.json({ ok: true }); });
    app.post('/api/admin/team/invite', async c => { const user = c.get('user'); if (user.role !== 'owner') return c.json({ error: 'Owner permission required.' }, 403); const input = z.object({ email: z.string().email().max(150), role: z.enum(['administrator', 'product_manager', 'support']) }).parse(await c.req.json()); const result = await repo.change(s => { if (s.invitations.some(i => i.email === input.email && i.status === 'pending')) return false; s.invitations.push({ ...input, id: crypto.randomUUID(), status: 'pending', createdAt: new Date().toISOString() }); audit(s, user, 'Staged invitation (not sent)', input.email); return true; }); return result ? c.json({ ok: true }) : c.json({ error: 'An invitation is already pending.' }, 409); });
    app.post('/api/admin/team/:id/suspend', async c => { const user = c.get('user'); if (user.role !== 'owner') return c.json({ error: 'Owner permission required.' }, 403); const ok = await repo.change(s => { const member = s.users.find(u => u.id === c.req.param('id')); if (!member || member.role === 'owner' || member.role === 'customer') return false; member.status = member.status === 'active' ? 'suspended' : 'active'; audit(s, user, 'Changed staff access', member.name); return true; }); return ok ? c.json({ ok: true }) : c.json({ error: 'This membership cannot be changed.' }, 400); });
    app.post('/api/agent/activate', async c => { const data = z.object({ key: z.string().max(100), productId: z.string(), deviceId: z.string().min(3).max(100) }).parse(await c.req.json()); const digest = await hash(data.key); const result = await repo.change(s => { const l = s.licenses.find(l => l.keyHash === digest && l.productId === data.productId && l.status === 'active'); if (!l || (l.expiresAt && Date.parse(l.expiresAt) <= Date.now()) || (l.device && l.device !== data.deviceId)) return null; l.device = data.deviceId; return { licenseId: l.id, productId: l.productId, deviceId: l.device, preview: true, message: 'Preview activation accepted. Production signed leases are not enabled.' }; }); return result ? c.json(result) : c.json({ error: 'Activation could not be authorized.' }, 403); });
    return app;
}
